spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/dossiermedical
    username: postgres
    password: n
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}